Quick fixes (#7)
* Change any occurences of metadata in tsv format to csv, all metadata must be specified in csv file now

* Changed all occurrences of metadata_path to metadata_file, as they were used inconsistently, causing errors

* Quick bug fixes for random split parameters

* Fix count -> split_count, added training_percentage to default params

* sequence_encoding_strategy and sequence_encoding_type -> sequence_encoding

* Change MiXCRLoader.load from static method to object method for consistency

* Added cores_for_training as ML parameter

* Fix for metadata being stored in parsed yaml

* Temporary print statements for debugging

File "/orange/brusko/github/ImmuneML/source/encodings/kmer_frequency/KmerFrequencyEncoder.py", line 95, in _encode_repertoires
    encoded_repertoire_list, repertoire_names, labels, feature_annotation_names = zip(*repertoires)
ValueError: not enough values to unpack (expected 4, got 0)

* Added option for batch_size parameter for encoding, both inside and outside of ML

* Added option for batch_size parameter for encoding, both inside and outside of ML

* Added print statements for debugging test dataset having 0 examples

* Added print statements for debugging test dataset having 0 examples

* Added print statements for debugging test dataset having 0 examples

* Allow training_percentage to be specified as percentage in addition to decimal

* Add learn_model to encoder_params as it was learning model for test data as default

* Changed metadata file after filtering

* Removed print statements